In [1]:
#Data Cleaning and EDA

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math as m



import warnings
warnings.filterwarnings("ignore")

In [2]:
lawsdf = pd.read_excel("../Capstone/stategunlaw.xlsx")

In [3]:
lawsdf

,state,year,felony,invcommitment,invoutpatient,danger,drugmisdemeanor,alctreatment,alcoholism,relinquishment,...,expartedating,dvrosurrender,dvrosurrendernoconditions,dvrosurrenderdating,expartesurrender,expartesurrendernoconditions,expartesurrenderdating,dvroremoval,stalking,lawtotal
0,Alabama,1991,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,15
1,Alabama,1992,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
2,Alabama,1993,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
3,Alabama,1994,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
4,Alabama,1995,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,Wyoming,2016,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1496,Wyoming,2017,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
1497,Wyoming,2018,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1498,Wyoming,2019,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1499,Wyoming,2020,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7

In [6]:
TotalLaws = pd.pivot_table(data= lawsdf, values= 'lawtotal', index ='state', aggfunc = 'mean')
print(TotalLaws)

                 lawtotal
state
Alabama         12.166667
Alaska           5.466667
Arizona         10.833333
Arkansas        12.333333
California      87.633333
Colorado        18.333333
Connecticut     67.800000
Delaware        26.033333
Florida         21.800000
Georgia         10.166667
Hawaii          70.500000
Idaho            5.166667
Illinois        57.633333
Indiana         10.433333
Iowa            21.533333
Kansas          10.366667
Kentucky         6.833333
Louisiana       10.633333
Maine            9.933333
Maryland        51.166667
Massachusetts   91.833333
Michigan        23.200000
Minnesota       31.800000
Mississippi      7.166667
Missouri        11.000000
Montana          4.266667
Nebraska        21.500000
Nevada          11.166667
New Hampshire    9.766667
New Jersey      61.500000
New Mexico      10.466667
New York        57.166667
North Carolina  26.200000
North Dakota    12.400000
Ohio            17.700000
Oklahoma         9.800000
Oregon          24.233333
Pennsylvania    32.766667
Rhode Island    43.533333
South Carolina  15.366667
South Dakota     5.700000
Tennessee       19.033333
Texas           17.166667
Utah            12.233333
Vermont          4.966667
Virginia        13.533333
Washington      28.100000
West Virginia   17.366667
Wisconsin       22.166667
Wyoming          8.466667

In [8]:
missouri = lawsdf.query("state =='Missouri'")
misslaw = missouri.groupby("year")["alcoholism"].sum().round(2)
misslaw.head()

year
1991    1
1992    1
1993    1
1994    1
1995    1
Name: alcoholism, dtype: int64